# Generated by Django 5.0.2 on 2024-02-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_users_favoritenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(verbose_name='Цвет фона')),
                ('font_size', models.IntegerField(verbose_name='Размер шрифта')),
                ('font_color', models.TextField(verbose_name='Цвет шрифта')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
