# Generated by Django 5.0.2 on 2024-02-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_account_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isblocked',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Статус блокировки'),
        ),
    ]
